Repository obophenotype/cell-ontology, pull requests merged in 2022-04, with the labels that each got.

#1530 Add obsolete replaced_by check
  src/ontology/Makefile
  src/ontology/cl-odk.yaml
  src/sparql/obsolete-replaced_by-violation.sparql
Labels: tech

#1554 Fixes #1548 corneal epithelial cell edits
  src/ontology/cl-edit.owl
Labels: HuBMAP

#1555 Fixes #1503 Strip 'cell' from labels of 'pericyte cell' and 'perirenal adipocyte cell'
  src/ontology/cl-edit.owl
Labels: kidney
