Repository obophenotype/cell-ontology, pull requests merged in 2022-06, with the labels that each got.

#1620 Fixes #1581 NTR collecting duct intercalated cell type A
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP, kidney

#1625 Addresses #1604 hepatic progenitor cell
  src/ontology/cl-edit.owl
Labels: synonym, HuBMAP

#1595 Added cite and application to readme
  README.md
Labels: unreviewed

#1633 Addresses #1627 Update a_adding_term_cellxgene.md
  .github/ISSUE_TEMPLATE/a_adding_term_cellxgene.md
Labels: cellxgene

#1624 Addresses #1171 NTR hillock cell
  src/ontology/cl-edit.owl
Labels: new term request
