Repository obophenotype/cell-ontology, pull requests merged in 2022-03, with the labels that each got.

#1480 Closes #1475 NTR fallopian tube secretory epithelial cell
  src/ontology/cl-edit.owl
Labels: new term request

#1485 remove SIO_000658
  src/ontology/cl-edit.owl
Labels: tech

#1483 Update resolving_merge_conflicts.md
  docs/resolving_merge_conflicts.md
Labels: documentation

#1493 Fixes #1489 [Typo/Bug] Typo in synonym of CL:0002169
  src/ontology/cl-edit.owl
Labels: synonym, typo

#1487 Closes #1486 [NTR] Fallopian tube ciliated cell
  src/ontology/cl-edit.owl
Labels: new term request

#1525 Fixes #1524 corneal epithelial cell should be part_of the corneal epi…
  src/ontology/cl-edit.owl
Labels: HuBMAP

#1527 Fixes #1441 Create synonym_type_property 'abbreviation' for CL
  src/ontology/cl-edit.owl
Labels: enhancement, synonym
