Repository obophenotype/cell-ontology, pull requests merged in 2022-09, with the labels that each got.

#1697 Addresses #1680 macrophage synonyms
  src/ontology/cl-edit.owl
Labels: synonym

#1694 remove "not" in CL
  src/ontology/cl-edit.owl
Labels: tech

#1702 Addresses #1698 edit synonym for leukocyte
  src/ontology/cl-edit.owl
Labels: synonym

#1679 Add lymphoblast and B-lymphoblast
  src/ontology/cl-edit.owl
Labels: new term request, unreviewed
