Repository obophenotype/cell-ontology, pull requests merged in 2023-04, with the labels that each got.

#1924 Addresses #1923 Add full stop to text definition
  src/ontology/cl-edit.owl
Labels: typo, maintenance

#1936 Addresses #1926 fix equivalence axiom of 'Schwann cell'
  src/ontology/cl-edit.owl
Labels: bug, typo, maintenance

#1934 Fixes #1933 text and logical definition club cell
  src/ontology/cl-edit.owl
Labels: logical definition, HuBMAP

#1951 Fix the hemocytes hierarchy
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy

#1954 Fixes #1901 Oenocyte definition
  src/ontology/cl-edit.owl
Labels: text definition

#1940 Addresses #1910 Build eye slim
  docs/odk-workflows/RepositoryFileStructure.md
  src/ontology/Makefile
  src/ontology/catalog-v001.xml
  src/ontology/cl-edit.owl
  src/ontology/cl-odk.yaml
  src/ontology/cl.Makefile
  src/ontology/components/eye_upper_slim.owl
  src/templates/eye_upper_slim.csv
Labels: slim
