Repository obophenotype/cell-ontology, pull requests merged in 2023-09, with the labels that each got.

#2132 Fixes #2102 duplicated label to synonym
  src/ontology/cl-edit.owl
Labels: synonym

#2143 Addresses #2045 Make plural synonym annotations consistent
  src/ontology/cl-edit.owl
Labels: synonym, maintenance

#2145 Addresses #2144 NTR 'airway submucosal gland duct ciliated cell'
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#2149 Addresses #2148 Edit text definition of 'L2/3 intratelencephalic projecting glutamatergic neuron of the primary motor cortex'
  src/ontology/cl-edit.owl
Labels: text definition

#2146 Fixes #2139 add synonym 'luteal cell'
  src/ontology/cl-edit.owl
Labels: synonym

#2147 Addresses #2124 Obsolete 'native cell' and 'animal cell'
  src/ontology/cl-edit.owl
Labels: obsoletion request, CL-classhierarchy

#2151 Addresses #1150 Obsolete 'somatic cell'
  src/ontology/cl-edit.owl
Labels: obsoletion request, CL-classhierarchy

#1806 Name shortening for BDS terms
  src/ontology/cl-edit.owl
Labels: unreviewed

#2161 Addresses #2160 Delete reports folder from root
  reports/cl-edit-obo-report.tsv
  reports/cl-edit.owl-obo-report.tsv
  reports/cl-obo-report.tsv
  reports/cl.owl-obo-report.tsv
Labels: maintenance
