Repository obophenotype/cell-ontology, pull requests merged in 2023-10, with the labels that each got.

#2163 Addresses #2158 Refine subclasses of 'kidney cell'
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, text definition, kidney

#2162 Addresses #2140 [NTR] 'TCR-positive macrophage'
  src/ontology/cl-edit.owl
Labels: new term request

#2165 Fixes #2164 unsat for syncytiotrophoblast cell
  src/ontology/cl-edit.owl
  src/ontology/imports/uberon_terms.txt
Labels: HuBMAP, need to resolve unsats

#2170 Fixes #2166 revision of Hofbauer cell
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#2181 Addresses #2154 [NTR-cxg] cortical region-agnostic L2/3-6 intratelencephalic projecting glutamatergic cortical neuron (by layer)
  src/ontology/cl-edit.owl
Labels: new term request, CL-classhierarchy, cellxgene

#2186 Fixes #2183 update reference term for general upper level slim
  src/ontology/cl.Makefile
Labels: maintenance, slim

#2188 EDIT PURL for abbreviation in editing_guidelines.md
  docs/editing_guidelines.md
Labels: documentation

#2189 Adresses #2179 NTR lactocyte subtypes
  src/ontology/cl-edit.owl
Labels: new term request, cellxgene

#2190 Addresses #1915 edit 'chandelier cell'
  src/ontology/cl-edit.owl
Labels: synonym, CL-classhierarchy, logical definition, text definition

#2187 Addresses #2180 NTR mammary luminal epithelial cells
  src/ontology/cl-edit.owl
  src/ontology/imports/pr_terms.txt
Labels: new term request, cellxgene

#2196 Addresses #2178 relabel and edit 'mammary alveolar cell'
  src/ontology/cl-edit.owl
Labels: synonym, CL-classhierarchy, text definition, relabel

#2201 Fixes #2200 edit lactocyte textual definition
  src/ontology/cl-edit.owl
Labels: text definition

#2206 Addresses #1149 obsolete 'barrier epithelial cell' and 'seminal flui…
  src/ontology/cl-edit.owl
Labels: obsoletion request
