Repository obophenotype/cell-ontology, pull requests merged in 2023-01, with the labels that each got.

#1792 Addresses #1781 text definition typo for iridophore
  src/ontology/cl-edit.owl
Labels: typo

#1790 [NTR] 'dental pulp stem cell' + edits to 'dental pulp cell' #1789
  src/ontology/cl-edit.owl
Labels: new term request

#1794 Addresses #1785 Edits to 'stromal cell of endometrium'
  src/ontology/cl-edit.owl
Labels: synonym, text definition

#1797 Addresses #1780 text definition typo in 'anterior lateral line neuromast mantle cell'
  src/ontology/cl-edit.owl
Labels: typo, text definition

#1801 Addresses #1779 fix typo and change parent term in 'Apocrine cell'
  src/ontology/cl-edit.owl
Labels: typo, text definition

#1805 Update CL relations_guide.md
  docs/relations_guide.md
Labels: documentation

#1818 Addresses #1816 Add synonym "metazoan cell" to "animal cell"
  src/ontology/cl-edit.owl
Labels: synonym

#1804 Addresses #1784 merge
  src/ontology/cl-edit.owl
Labels: merge
