Repository obophenotype/cell-ontology, pull requests merged in 2023-03, with the labels that each got.

#1869 Addresses #1868 typo Parasol GCR
  src/ontology/cl-edit.owl
Labels: typo, text definition

#1871 Addresses #1870 NTR retinal astrocyte
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#1872 Fixes #1866 bug GnRH neuron
  src/ontology/cl-edit.owl
Labels: bug, HuBMAP

#1873 Addresses #1856 NTR- CD24+, CD-133+, vimentin+ proximal tubular cell
  src/ontology/cl-edit.owl
Labels: new term request, kidney

#1877 Addresses #1876 SYN photoreceptors
  src/ontology/cl-edit.owl
Labels: synonym

#1882 Addresses #1867 add 'anatomical structure' superclass to cell
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy

#1891 Addresses #1879 EA Megakaryocyte
  src/ontology/cl-edit.owl
Labels: logical definition, text definition, HuBMAP

#1897 Fixes #1885 logical definition endocrine cell
  src/ontology/cl-edit.owl
Labels: logical definition
