Repository obophenotype/cell-ontology, pull requests merged in 2023-11, with the labels that each got.

#2213 Fixes #2212 class hierarchy 'peritubular capillary endothelial cell'
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#2210 Fixes #2209 relabel fat cell
  src/ontology/cl-edit.owl
Labels: text definition, relabel, HuBMAP

#2208 Fixes #1266 populate mononuclear phagocyte
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy

#2222 Addresses #2203 [NTR-cxg] 'L5/6 near-projecting glutamatergic neuron'
  src/ontology/cl-edit.owl
  src/ontology/cl-idranges.owl
Labels: new term request, cellxgene

#2218 Update README.md
  README.md
Labels: documentation

#2229 Addresses #2224 Edit 'epithelial cell of lacrimal duct'
  src/ontology/cl-edit.owl
Labels: synonym, logical definition, text definition

#2234 Addresses #2202 NTR 'L6 IT Car3 glutamatergic neuron'
  src/ontology/cl-edit.owl
  src/ontology/imports/pr_terms.txt
Labels: new term request, cellxgene
