Repository obophenotype/cell-ontology, pull requests merged in 2023-02, with the labels that each got.

#1825 Addresses #1814 [NTR] early and late spermatid
  src/ontology/cl-edit.owl
Labels: new term request

#1831 Addresses #5 Edit ciliary epithelial cells
  src/ontology/cl-edit.owl
Labels: typo, text definition

#1819 Addresses #1811 NTR 'respiratory ciliated cell'
  src/ontology/cl-edit.owl
Labels: new term request

#1832 Addressess #1726 Edit perineurial cell
  src/ontology/cl-edit.owl
Labels: typo, text definition, HuBMAP

#1838 Grammar fix in PR #1832
  src/ontology/cl-edit.owl
Labels: typo, text definition

#1826 Resolve #1813 NTR suprabasal keratinocyte
  src/ontology/cl-edit.owl
Labels: new term request

#1828 Addresses #1827 NTR peg cell
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#1845 Addresses #1833 typo KDNy
  src/ontology/cl-edit.owl
Labels: typo
