Repository obophenotype/cell-ontology, pull requests merged in 2023-05, with the labels that each got.

#1959 Addresses #1956 NTR lung TRM
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#1977 Fixes #1976 chemoreceptors
  src/ontology/cl-edit.owl
Labels: logical definition

#1978 Addresses #515 Update 'glomerular mesangial cell'
  src/ontology/cl-edit.owl
Labels: KPMP, kidney

#1981 Addresses #114 NTR catecholaminergic neuron
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#1992 Fixes #1991 myofibroblast part of connective tissue
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#1993 Fixes #1986 platelet EA
  src/ontology/cl-edit.owl
Labels: logical definition

#1998 Addresses #1990 NTR 'von Economo neuron'
  src/ontology/cl-edit.owl
Labels: new term request
