Repository obophenotype/cell-ontology, pull requests merged in 2023-08, with the labels that each got.

#2085 Addresses #2012 Edit 'olfactory granule cell'
  src/ontology/cl-edit.owl
Labels: synonym, logical definition, text definition, BICAN

#2091 Fixes #1925 abbreviation related synonyms
  src/ontology/cl-edit.owl
Labels: synonym

#2090 Addresses #2000 NTR retinal ganglion cells
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#2098 Addresses #427 obsolete 'acid secreting cell' and edit 'parietal cell'
  src/ontology/cl-edit.owl
Labels: obsoletion request

#2104 Addresses #2103 Edit 'pain receptor cell'
  src/ontology/cl-edit.owl
Labels: synonym

#2115 Update editing_guidelines.md re: MeSH cross-references
  docs/editing_guidelines.md
Labels: documentation

#2116 Update guidance on adding URL dbxrefs (editing_guidelines.md)
  docs/editing_guidelines.md
Labels: documentation

#2120 Addresses #2119 NTR perivascular cell
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP, cellxgene

#2096 Fixes #2082 classifies amacrine cells GABA vs glycine and dendrite field
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#2129 Addresses #2126 Edit 'polyploid cell'
  src/ontology/cl-edit.owl
Labels: logical definition, text definition

#2130 Edited editing_guidelines.md regarding cross-references
  docs/editing_guidelines.md
Labels: documentation

#2131 Addresses #2101 Update synonym type on "subcapsular thymic epithelial…
  src/ontology/cl-edit.owl
Labels: synonym
