Repository obophenotype/cell-ontology, pull requests merged in 2023-06, with the labels that each got.

#2009 Addresses #2007 text def 'granule cell'
  src/ontology/cl-edit.owl
Labels: text definition

#2011 Addresses #1997 Fix dbxref URLs
  src/ontology/cl-edit.owl
Labels: maintenance

#2016 Addresses #2015 Update definitions for bladder urothelial cell types
  src/ontology/cl-edit.owl
Labels: logical definition, text definition

#2014 Addresses #2008 edit 'medium spiny neuron'
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, text definition

#2025 Addresses #2022 edit 'urothelial cell'
  src/ontology/cl-edit.owl
Labels: synonym, text definition

#2029 Addresses #2021 [Update] Edit 'basal cell of urothelium'
  src/ontology/cl-edit.owl
Labels: synonym, CL-classhierarchy, text definition

#2033 Addresses 2028 NTR lung terms
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#1979 Addresses #1908 to create an upper cell type slim
  docs/odk-workflows/RepositoryFileStructure.md
  src/ontology/Makefile
  src/ontology/catalog-v001.xml
  src/ontology/cl-edit.owl
  src/ontology/cl-odk.yaml
  src/ontology/cl.Makefile
  src/ontology/components/eye_upper_slim.owl
  src/ontology/components/general_cell_types_upper_slim.owl
  src/templates/general_cell_types_upper_slim.csv
Labels: slim

#1984 Make 'primary neuron' teleost-specific.
  src/ontology/cl-edit.owl
Labels: unreviewed

#2041 Addresses #2037 NTR 'eccentric medium spiny neuron'
  src/ontology/cl-edit.owl
Labels: new term request, BICAN

#2046 Addresses #2044 retina cell type syns
  src/ontology/cl-edit.owl
Labels: synonym
