Repository obophenotype/cell-ontology, pull requests merged in 2023-07, with the labels that each got.

#2050 Fixes #2049 add soma location OFF-bipolar cell
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#2047 Fixes #2042 folliculostellate cell
  src/ontology/cl-edit.owl
Labels: synonym, CL-classhierarchy, text definition

#2055 Addresses #2054 Replaced synapsed_by with 'synapsed by' in 'cartwheel…
  src/ontology/cl-edit.owl
Labels: maintenance, BICAN

#2057 Addresses #2056 Deleted synapsed_by from CL
  src/ontology/cl-edit.owl
Labels: maintenance, BICAN

#2062 Fixes #2061 hierarchy bronchiolar smooth muscle cell
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#2060 Addresses #2059 Add logical definition and synonym to lung megakaryocyte
  src/ontology/cl-edit.owl
Labels: synonym, logical definition, HuBMAP

#2058 Update editor guidelines re: standardising database_cross_reference and contributor annotations
  docs/editing_guidelines.md
Labels: documentation

#2067 Addresses #2012 edit cerebellar granule cell and precursor
  src/ontology/cl-edit.owl
Labels: synonym, text definition, BICAN

#2072 Fixes #2071 'endothelial cell of respiratory system lymphatic vessel'
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#2070 Addresses #2012 Edit 'dentate gyrus of hippocampal formation granule cell'
  src/ontology/cl-edit.owl
Labels: synonym, CL-classhierarchy, text definition, BICAN

#2075 Fixes #2074 pulmonary capillary endothelial cell location
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#2078 Addresses #2053 Establish standard for CL labels with anatomical ref…
  docs/editing_guidelines.md
Labels: documentation
