Repository obophenotype/cell-ontology, pull requests merged in 2024-04, with the labels that each got.

#2323 Fixes #2318 edit myoepithelial cell of mammary gland
  src/ontology/cl-edit.owl
Labels: synonym, text definition, relabel, HuBMAP

#2319 NTR-border-associated-macrophage
  src/ontology/cl-edit.owl
Labels: new term request

#2334 Fixes #2324 synonym terminal Schwann cell
  src/ontology/cl-edit.owl
Labels: synonym

#2338 Add Jorstad paper as a reference to cortical neuron CL terms
  src/ontology/cl-edit.owl
Labels: BICAN

#2353 Fixes #1562 merge foreskin melanocyte and melanocyte of foreskin
  src/ontology/cl-edit.owl
Labels: merge

#2347 Re-classify 'R7 photoreceptor cell' as part of an ommatidium.
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy

#2356 Fixes #2288 NTR preplasmablast
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP
