Repository obophenotype/cell-ontology, pull requests merged in 2024-09, with the labels that each got.

#2492 Fixes #2422 develops_from axiom on blood vessel endothelial cell strict
  src/ontology/cl-edit.owl
Labels: HCA/DCP, CL-classhierarchy, HuBMAP

#2541 Fixes #2538 Text definition CD1c-positive myeloid dendritic cell
  src/ontology/cl-edit.owl
Labels: text definition

#2504 new term immature pericyte added
  src/ontology/cl-edit.owl
Labels: HCA/DCP, cellxgene

#2512 NTR-astrocyte-restricted-precursor-and-neuronal-restricted-precursor
  src/ontology/cl-edit.owl
Labels: new term request, BICAN

#2597 Update cl-edit.owl
  src/ontology/cl-edit.owl
Labels: update-imports-required

#2598 Add a LHX6 marker to TAC3-positive striatal interneuron definition
  src/ontology/cl-edit.owl
Labels: HCA/DCP, text definition, BICAN

#2536 mge-derived-cortical-interneuron-hierarchy
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, BICAN

#2599 change label of caudal ganglionic eminence derived interneuron
  src/ontology/cl-edit.owl
Labels: Priority-High, HCA/DCP, relabel, BICAN

#2608 Fixes #2602 NTR granulosa cells and remake class hierarchy
  src/ontology/cl-edit.owl
Labels: new term request, CL-classhierarchy

#2566 NTR-substantia-nigra-dopaminergic-neuron-for-Basal-Ganglia-BICAN
  src/ontology/cl-edit.owl
Labels: new term request, HCA/DCP, BICAN

#2473 logical definition photoreceptor update
  src/ontology/cl-edit.owl
Labels: update-imports-required

#2612 Add-t-type-definition-to-all-the-Jorstad-CrossArea_Subclass-with-CxG-reference
  src/ontology/cl-edit.owl
Labels: Priority-High, definition request, BICAN

#2606 Add documentation on adding PRO terms
  docs/Adding_classes_from_another_ontology.md
Labels: documentation

#2618 Address #2617 wrong AP for definition of pSNpr
  src/ontology/cl-edit.owl
Labels: bug
