Repository obophenotype/cell-ontology, pull requests merged in 2024-11, with the labels that each got.

#2710 Add-text-definition-to-peripheral-sensory-neuron,-polymodal-neuron,-c…
  src/ontology/cl-edit.owl
Labels: text definition, BICAN

#2715 Fixes #2694 NTR placental resident macrophages
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#2733 Fixes #2732 ntr cxg atretic theca cell
  src/ontology/cl-edit.owl
Labels: new term request, cellxgene

#2738 pre-venule capillary cell
  src/ontology/cl-edit.owl
Labels: HCA/DCP, cellxgene, GutCellAtlas

#2731 Fixes #2673 NTR CxG type IIx muscle cell
  src/ontology/cl-edit.owl
Labels: new term request, cellxgene

#2745 adjust-the-hierarchy-CNS-nematoda-and-CNS-vertebrata
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, BICAN

#2740 secretory pericyte
  src/ontology/cl-edit.owl
Labels: HCA/DCP, cellxgene, GutCellAtlas

#2758 NTR-grouping-term-caudal-ganglionic-eminence-derived-neuron
  src/ontology/cl-edit.owl
Labels: new term request, BICAN

#2790 Fixes #2775 rename lung neuroendocrine cell
  src/ontology/cl-edit.owl
Labels: Lung_refactor

#2773 NTR-glutametergic-neuron-of-the-basal-ganglia
  src/ontology/cl-edit.owl
Labels: new term request, BICAN

#2798 NTR-glutamatergic-neuron-of-the-thalamus
  src/ontology/cl-edit.owl
Labels: new term request, BICAN

#2794 SI images added
  src/ontology/cl-edit.owl
Labels: HCA/DCP, GutCellAtlas

#2814 CL images
  images/Colon-cells.png
  images/README.md
  images/SI-colon-layers.png
  images/Small-intestine-cells.png
Labels: HCA/DCP, cellxgene, GutCellAtlas
