Repository obophenotype/cell-ontology, pull requests merged in 2024-06, with the labels that each got.

#2390 Update Brain Data Standards paper on README.md
  README.md
Labels: documentation

#2392 Addresses #2360 NTR mural granulosa cell and pre-granulosa cell
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#2403 Fixes #2169 relabel lung cell types
  src/ontology/cl-edit.owl
Labels: text definition, relabel, HuBMAP, Lung_refactor
