Repository obophenotype/cell-ontology, pull requests merged in 2024-12, with the labels that each got.

#2823 Fixes #2818 NTR GABA-Gly AC
  src/ontology/cl-edit.owl
Labels: new term request, HCA/DCP, HuBMAP

#2674 separating_gut_meosthelial_from_gut_lining
  src/ontology/cl-edit.owl
Labels: GutCellAtlas

#2857 Fixes #2855 NTR limbal epithelial stem cell
  src/ontology/cl-edit.owl
  src/ontology/imports/uberon_terms.txt
Labels: new term request, HuBMAP

#2686 Merge cns interneuron interneuron term
  src/ontology/cl-edit.owl
  src/ontology/components/hra_subset.owl
  src/ontology/components/mappings.owl
Labels: CL-classhierarchy, BICAN

#2870 Fixes 2869 wrongly obsoleted 'CNS interneuron'
  src/ontology/cl-edit.owl
  src/ontology/components/hra_subset.owl
Labels: obsoletion request
