Repository obophenotype/cell-ontology, pull requests merged in 2024-07, with the labels that each got.

#2407 Enterocyte of colon synonym added
  src/ontology/cl-edit.owl
Labels: synonym

#2420 Schwann cell precursor typo
  src/ontology/cl-edit.owl
Labels: typo

#2431 Adresses #2425 class hierarchy 'vasa recta cell'
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#2434 Remove misused `owl:deprecated: false`
  src/ontology/cl-edit.owl
Labels: bug

#2432 VIP-ChAT-neuron-and-spiny-VIP-neuron-new-term-request
  src/ontology/cl-edit.owl
Labels: new term request, BICAN

#2433 NTR Nasal serous secreting cells
  src/ontology/cl-edit.owl
Labels: new term request

#2438 Text def Purkinje neuron
  src/ontology/cl-edit.owl
Labels: text definition, BICAN
