Repository obophenotype/cell-ontology, pull requests merged in 2024-08, with the labels that each got.

#2487 Adresses #2261 edit trophoblast cell text definition and hierarchy to describe origin and location
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, text definition

#2494 Fixes #2493 refactoring blood vessel endothelial cells
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy, HuBMAP

#2489 t-type-GABAergic-VIP-cortical-interneuron-definition
  src/ontology/cl-edit.owl
Labels: text definition, BICAN

#2501 Fixes #2480 Refactor multinucleated cells and subclasses
  src/ontology/cl-edit.owl
Labels: new term request, CL-classhierarchy, text definition

#2520 Fixes #2479 Added textual and logical definition for stratified epithelial cell and subclasses
  src/ontology/cl-edit.owl
Labels: logical definition, text definition

#2511 Fixes #2510 Revise ependymal cell and subclasses
  src/ontology/cl-edit.owl
Labels: logical definition, text definition
