Repository obophenotype/cell-ontology, pull requests merged in 2024-10, with the labels that each got.

#2625 Fixes #2485 NTR - pancreatic islet capillary endothelial cell
  src/ontology/cl-edit.owl
Labels: new term request

#2571 Fibroblasts are stromal
  src/ontology/cl-edit.owl
Labels: CL-classhierarchy

#2667 Update monthly call times in README
  README.md
Labels: documentation

#2635 NTR Immature neurons and immature cortical neurons
  src/ontology/cl-edit.owl
Labels: new term request, BICAN

#2650 NTR candelabrum cell
  src/ontology/cl-edit.owl
Labels: new term request, BICAN

#2664 Fixes #2651 NTR diffuse bipolar 5 cell
  src/ontology/cl-edit.owl
Labels: new term request, HCA/DCP, HuBMAP

#2701 Fixes #2700 remove colonocyte synonym
  src/ontology/cl-edit.owl
Labels: synonym, HuBMAP

#2649 NTR-pro-opiomelanocortin-neuron
  src/ontology/cl-edit.owl
Labels: new term request, BICAN
