Repository obophenotype/cell-ontology, pull requests merged in 2025-01, with the labels that each got.

#2751 Adjust hierarchy of somatosensory neurons (sensu Teleostei)
  src/ontology/cl-edit.owl
Labels: new term request, CL-classhierarchy, BICAN

#2883 Add step to clean temporary files in cl release documentation
  docs/cl-release.md
Labels: documentation

#2884 Adresses #2791 NTR age-associated B cell
  src/ontology/cl-edit.owl
Labels: new term request, HuBMAP

#2900 Fixes #2892 NTR diffuse bipolar 4a and 4b cells
  src/ontology/cl-edit.owl
Labels: new term request, HCA/DCP, HuBMAP

#2918 Fixes #2903 tuft cell of nasal cavity
  src/ontology/cl-edit.owl
Labels: new term request, cellxgene
